/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  content: ["./App.tsx", "./index.ts", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Direct mappings to layout CSS custom properties (light/dark via .dark)
        "layout-main": "var(--bg-main)",
        "layout-surface": "var(--bg-surface)",
        "layout-elevated": "var(--bg-elevated)",
        "layout-subtle": "var(--bg-subtle)",
        "layout-hover": "var(--bg-hover)",
        "card-surface": "var(--card-surface)",
        "card-hover": "var(--card-hover-bg)",
        "border-layout": "var(--border-color)",
        "border-layout-subtle": "var(--border-subtle)",
        "border-layout-hover": "var(--border-hover)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-subtle": "var(--text-subtle)",
        "navbar-bg": "var(--navbar-bg)",
        "navbar-border": "var(--navbar-border)",
        "navbar-btn": "var(--navbar-btn-bg)",
        "navbar-btn-border": "var(--navbar-btn-border)",
        "navbar-btn-text": "var(--navbar-btn-text)",
        "navbar-dropdown": "var(--navbar-dropdown-bg)",
        "navbar-dropdown-border": "var(--navbar-dropdown-border)",
        "sidebar-bg": "var(--sidebar-bg)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-item": "var(--sidebar-item-text)",
        "sidebar-item-active": "var(--sidebar-item-active-text)",
        "accent-blue": "var(--accent-blue)",
        "accent-blue-subtle": "var(--accent-blue-subtle)",
        "accent-emerald": "var(--accent-emerald)",
        "accent-emerald-subtle": "var(--accent-emerald-subtle)",
      },
      fontFamily: {
        vazir: ["Vazirmatn"],
        "vazir-medium": ["Vazirmatn-Medium"],
        "vazir-semibold": ["Vazirmatn-SemiBold"],
        "vazir-bold": ["Vazirmatn-Bold"],
        "vazir-light": ["Vazirmatn-Light"],
        "vazir-extrabold": ["Vazirmatn-ExtraBold"],
      },
    },
  },
};
